### ISSUE TITLE
Bookmarkie works only once after starting browser

### ISSUE THREAD

**Issue by mooop12** [angusjune/bookmarkie#1]
So I get this error in all the other forks of neater bookmarks as well, but this seems to be the most recent so I'm creating the issue here. After starting the browser, the bookmarkie button works once, and then after clicking it nothing happens, the button just appears clicked but there is no pop-up. I have a large number of bookmarks so that may be the cause. I don't know how to debug chrome extensions, but if you have any ideas let me know and I'll help.

**Comment by angusjune** [comment]
@mooop12 That's weird. I haven't encountered this kind of situation myself. Would you mind telling me the version of your Chrome as well as your system?

**Comment by mooop12** [comment]
Chrome 58.0.3029.110 on Linux.

**Comment by mooop12** [comment]
This doesn't happen on Windows, I just checked. Any ideas?

**Comment by mooop12** [comment]
A quick update, now after clicking bookmarkie icon the whole browser crashes.
