### ISSUE TITLE
不能用它新建文件夹

### ISSUE THREAD

**Issue by sherlocknieh** [angusjune/bookmarkie#3]
如果有可能的话，我需要 “创建文件夹、多选、批量移动书签” 等功能，希望作者能看到

**Comment by angusjune** [comment]
Bookmarkie 定位是一个轻量的书签查看器（甚至不是管理器），所以可能暂时不会添加比较复杂的管理操作。
不过我会在更新版本中添加前往 Chrome 自带书签管理器的链接。

**Comment by angusjune** [comment]
在最近的更新中（v2.0.0），你可以右键点击浏览器右上角 icon，以前往 Chrome 自带书签管理器
